### PR TITLE
Update PHP_flow-jsonpath

### PR DESCRIPTION
**Pull request by SoftCreatR**
The [original lib](https://github.com/FlowCommunications/JSONPath) has been abandoned is superseded by [SoftCreatR/JSONPath](https://github.com/SoftCreatR/JSONPath)

### CODE REVIEW

**Comment by cburgmer** [comment]
Running this locally gives me the following:

```
$ LANG=en_US.UTF-8 LC_ALL= LC_COLLATE=C ./src/wrap_in_docker.sh ./src/query_implementation.sh queries/filter_expression_with_equals_true implementations/PHP_flow-jsonpath
[...]
ERROR
This error message includes an absolute path which will make it hard to reproduce on other machines.
Please change the script to error without it.

PHP Fatal error:  Uncaught TypeError: strtolower() expects parameter 1 to be string, bool given in /json-path-comparison/implementations/PHP_flow-jsonpath/vendor/softcreatr/jsonpath/src/Filters/QueryMatchFilter.php:65
Stack trace:
#0 /json-path-comparison/implementations/PHP_flow-jsonpath/vendor/softcreatr/jsonpath/src/Filters/QueryMatchFilter.php(65): strtolower()
#1 /json-path-comparison/implementations/PHP_flow-jsonpath/vendor/softcreatr/jsonpath/src/JSONPath.php(67): Flow\JSONPath\Filters\QueryMatchFilter->filter()
#2 /json-path-comparison/implementations/PHP_flow-jsonpath/main.php(14): Flow\JSONPath\JSONPath->find()
#3 {main}
  thrown in /json-path-comparison/implementations/PHP_flow-jsonpath/vendor/softcreatr/jsonpath/src/Filters/QueryMatchFilter.php on line 65
```

**Comment by SoftCreatR** [comment]
Well, that's strange. It worked fine during my test. But I'll check that.

**Comment by SoftCreatR** [comment]
Fixed it. I've created a small script that executes all queries against this specific implementation, so I didn't had to execute all the unrelated stuff.

Here's the log:

```
queries/bracket_notation_with_number_-1_on_empty_array
OK
[]


queries/array_slice_with_start_-1_and_open_end
OK
["third"]


queries/dot_notation_after_bracket_notation_with_wildcard
OK
[1, 1]


queries/dot_notation_with_wildcard_after_recursive_descent_on_null_value_array
OK
[40, 42, null]


queries/array_slice_on_object
OK
[]


queries/filter_expression_with_tautological_comparison
ERROR
Error: 'Malformed filter query'


queries/dot_notation_on_array_with_containing_object_matching_key
OK
[]


queries/filter_expression_with_equals_array_for_dot_notation_with_star
OK
[]


queries/filter_expression_with_equals_string
OK
[{"key": "value"}, {"key": 0}]


queries/array_slice_with_negative_start_and_end_and_range_of_0
OK
[]


queries/bracket_notation_with_quoted_array_slice_literal
OK
["value"]


queries/bracket_notation_with_number_-1
OK
["third"]


queries/array_slice_with_range_of_1
OK
["first"]


queries/array_slice_with_positive_start_and_negative_end_and_range_of_0
OK
[]


queries/array_slice_with_positive_start_and_negative_end_and_range_of_-1
OK
[]


queries/filter_expression_with_value_true
ERROR
Error: 'Malformed filter query'


queries/dot_notation_with_wildcard_on_empty_array
OK
[]


queries/array_slice_with_negative_step_and_start_greater_than_end
SKIPPED


queries/dot_notation_after_bracket_notation_with_wildcard_on_one_matching
OK
[1]


queries/array_slice_with_negative_start_and_positive_end_and_range_of_1
OK
[4]


queries/bracket_notation_with_string_including_dot_wildcard
OK
[1]


queries/union_with_spaces
OK
["first", "second"]


queries/array_slice_with_range_of_0
OK
[]


queries/bracket_notation_with_number_on_object
OK
["value"]


queries/filter_expression_with_value_false
ERROR
Error: 'Malformed filter query'


queries/filter_expression_with_set_wise_comparison_to_set
OK
[]


queries/filter_expression_with_equals_number_with_fraction
OK
[{"key": -12.3}, {"key": "-0.123e2"}]


queries/filter_expression_with_bracket_notation_with_number_on_object
OK
[["a", "b"]]


queries/root_on_scalar_false
OK
[false]


queries/bracket_notation_with_NFC_path_on_NFD_key
OK
[]


queries/bracket_notation_with_quoted_dot_wildcard
OK
[1]


queries/dot_notation_with_double_quotes_after_recursive_descent
OK
["russian dolls", "something", "top", "value", {"key": "russian dolls"}]


queries/array_slice_with_large_number_for_end_and_negative_step
OK
[]


queries/filter_expression_with_bracket_notation_with_-1
OK
[]


queries/filter_expression_with_in_current_object
ERROR
Error: 'Malformed filter query'


queries/union_with_repeated_matches_after_dot_notation_with_wildcard
OK
["string", null, true, false, "string", 5.4]


queries/script_expression
OK
["fifth"]


queries/filter_expression_with_equals_array_with_single_quotes
OK
[{"d": ["v1", "v2"]}]


queries/filter_expression_with_boolean_and_operator
OK
[{"key": 43}, {"key": 44}]


queries/filter_expression_with_equals_false
OK
[{"key": false}, {"key": null}, {"key": ""}, {"key": 0}, {"key": []}]


queries/filter_expression_with_value
OK
[{"key": true}, {"key": "value"}, {"key": 1}, {"key": -1}, {"key": 42}, {"key": {}}]


queries/filter_expression_with_not_equals
OK
[]


queries/recursive_descent
OK
[[0, 1], [{"a": {"b": "c"}}, [0, 1]], {"a": {"b": "c"}}, {"b": "c"}]


queries/dot_notation_with_wildcard_after_dot_notation_with_wildcard_on_nested_arrays
OK
[1, 2, 3, 4, 5, 6]


queries/bracket_notation_with_number
OK
["third"]


queries/filter_expression_with_equals
OK
[{"key": 42}, {"key": "42"}]


queries/dot_notation_on_object_without_key
OK
[]


queries/filter_expression_with_negation_and_equals
ERROR
Error: 'Malformed filter query'


queries/bracket_notation_with_empty_string_doubled_quoted
NOT_SUPPORTED
Error: 'Unable to parse token "" in expression: [""]'


queries/dot_notation_with_number_-1
OK
["fifth"]


queries/bracket_notation_with_double_quotes
OK
["value"]


queries/filter_expression_with_set_wise_comparison_to_scalar
OK
[]


queries/filter_expression_with_equals_on_object
OK
[{"key": 42}]


queries/dot_bracket_notation_with_double_quotes
OK
["value"]


queries/filter_expression_with_less_than
OK
[]


queries/array_slice_with_negative_step_on_partially_overlapping_array
OK
[]


queries/array_slice_with_open_start_and_end_on_object
OK
[]


queries/union_with_wildcard_and_number
NOT_SUPPORTED
Error: 'Unable to parse token *,1 in expression: [*,1]'


queries/union
OK
["first", "second"]


queries/array_slice_with_open_end_and_negative_step
SKIPPED


queries/root
OK
[{"another key": {"complex": ["a", 1]}, "key": "value"}]


queries/filter_expression_with_regular_expression
OK
[]


queries/filter_expression_without_parens
NOT_SUPPORTED
Error: 'Unable to parse token ?@.key==42 in expression: [?@.key==42]'


queries/dot_notation_after_filter_expression
OK
["forty-two"]


queries/array_slice_with_open_start_and_end_and_step_empty
OK
["first", "second"]


queries/dot_notation_with_key_named_true
OK
["value"]


queries/filter_expression_with_greater_than
OK
[]


queries/array_slice_with_positive_start_and_negative_end_and_range_of_1
OK
[5]


queries/dot_notation_after_union_with_keys
OK
[]


queries/dot_notation_with_key_named_in
OK
["value"]


queries/filter_expression_with_equals_boolean_expression_value
ERROR
Error: 'Malformed filter query'


queries/dot_notation_on_array
OK
[]


queries/bracket_notation_with_quoted_closing_bracket_literal
NOT_SUPPORTED
Error: 'Unable to parse token ' in expression: [']']'


queries/dot_notation_with_single_quotes_after_recursive_descent
OK
["russian dolls", "something", "top", "value", {"key": "russian dolls"}]


queries/bracket_notation_with_quoted_wildcard_literal_on_object_without_key
OK
["entry"]


queries/bracket_notation_with_dot
OK
["42"]


queries/dot_notation_on_array_value
OK
[["first", "second"]]


queries/array_slice_with_open_start_and_end
OK
["first", "second"]


queries/array_slice_with_negative_start_and_positive_end_and_range_of_0
OK
[]


queries/filter_expression_with_in_array_of_values
OK
[]


queries/bracket_notation_with_wildcard_on_object
OK
["string", 42, [0, 1], {"key": "value"}]


queries/bracket_notation_with_quoted_dot_literal
OK
["value"]


queries/filter_expression_with_boolean_and_operator_and_value_true
OK
[{"key": 1}, {"key": 3}, {"key": "nice"}, {"key": {}}, {"key": []}]


queries/bracket_notation_with_quoted_root_literal
OK
["value"]


queries/filter_expression_with_value_from_recursive_descent
OK
[]


queries/dot_notation_with_wildcard_on_object
OK
["string", 42, [0, 1], {"key": "value"}]


queries/array_slice_with_step_but_end_not_aligned
OK
["first", "third"]


queries/filter_expression_with_different_grouped_operators
ERROR
Error: 'Malformed filter query'


queries/bracket_notation_with_quoted_string_and_unescaped_single_quote
OK
["value"]


queries/filter_expression_with_equals_number_for_array_slice_with_range_1
OK
[]


queries/filter_expression_with_bracket_notation_and_current_object_literal
OK
[{"@key": 42}]


queries/filter_expression_with_boolean_and_operator_and_value_false
OK
[{"key": 1}, {"key": 3}, {"key": "nice"}, {"key": {}}, {"key": []}]


queries/bracket_notation_with_quoted_escaped_backslash
OK
[]


queries/bracket_notation_after_recursive_descent
OK
["deepest", "first nested", "first", "more", {"nested": ["deepest", "second"]}]


queries/filter_expression_with_equals_on_array_without_match
OK
[]


queries/filter_expression_with_boolean_or_operator
OK
[{"key": 44}]


queries/dot_notation_on_null_value
OK
[null]


queries/bracket_notation_with_number_on_string
OK
[]


queries/dot_notation_with_wildcard_on_array
OK
["string", 42, {"key": "value"}, [0, 1]]


queries/dot_notation_with_number
OK
["third"]


queries/array_slice_on_exact_match
OK
["first", "second", "third", "forth", "fifth"]


queries/union_with_numbers_in_decreasing_order
OK
[5, 2]


queries/bracket_notation_on_object_without_key
OK
[]


queries/union_with_keys_after_bracket_notation
OK
[]


queries/dot_notation_with_number_on_object
OK
["second"]


queries/dot_notation_with_single_quotes_and_dot
NOT_SUPPORTED
Error: 'Unable to parse token 'some in expression: .'some.key''


queries/filter_expression_with_division
OK
[{"key/10": 5}]


queries/dot_notation_with_single_quotes
OK
["value"]


queries/array_slice_on_partially_overlapping_array
OK
["second", "third"]


queries/array_slice
OK
["second", "third"]


queries/bracket_notation_without_quotes
OK
["value"]


queries/dot_notation_with_key_named_length_on_array
OK
[]


queries/filter_expression_with_equals_on_object_with_key_matching_query
OK
[]


queries/array_slice_with_range_of_-1
OK
[]


queries/bracket_notation_with_quoted_union_literal
OK
["value"]


queries/array_slice_with_open_end
OK
["second", "third", "forth", "fifth"]


queries/filter_expression_with_equals_array_for_array_slice_with_range_1
OK
[]


queries/bracket_notation_with_two_literals_separated_by_dot
OK
["43"]


queries/union_with_keys_after_dot_notation_with_wildcard
OK
[]


queries/dot_notation_with_wildcard_on_empty_object
OK
[]


queries/bracket_notation_with_quoted_escaped_single_quote
OK
[]


queries/array_slice_with_step_0
OK
["first", "second", "third"]


queries/dot_notation_with_key_named_length
OK
["value"]


queries/root_on_scalar
OK
[42]


queries/union_with_filter
OK
[]


queries/bracket_notation_with_empty_path
OK
[{"": 42, "\"\"": 222, "''": 123}]


queries/filter_expression_with_triple_equal
OK
[{"key": 0}]


queries/filter_expression_with_equals_array
OK
[{"d": ["v1", "v2"]}]


queries/bracket_notation_with_number_0
OK
["first"]


queries/dot_notation_with_wildcard_after_recursive_descent_on_scalar
OK
[]


queries/bracket_notation_with_wildcard_on_empty_object
OK
[]


queries/array_slice_with_negative_start_and_end_and_range_of_1
OK
[4]


queries/filter_expression_with_greater_than_or_equal
OK
[]


queries/filter_expression_with_current_object
ERROR
Error: 'Malformed filter query'


queries/dot_notation_after_recursive_descent_after_dot_notation
OK
[12.99, 19.95, 22.99, 8.95, 8.99]


queries/array_slice_with_start_-2_and_open_end
OK
["second", "third"]


queries/filter_expression_with_less_than_or_equal
OK
[]


queries/filter_expression_with_subfilter
OK
[]


queries/array_slice_with_negative_start_and_end_and_range_of_-1
OK
[]


queries/filter_expression_with_multiplication
OK
[{"key*2": 100}]


queries/array_slice_with_large_number_for_start
SKIPPED


queries/filter_expression_with_equals_number_for_bracket_notation_with_star
OK
[]


queries/filter_expression_with_subpaths
OK
[]


queries/filter_expression_with_subtraction
OK
[{"key-50": -100}]


queries/bracket_notation_with_wildcard_on_empty_array
OK
[]


queries/array_slice_with_open_start
OK
["first", "second"]


queries/filter_expression_with_value_null
ERROR
Error: 'Malformed filter query'


queries/filter_expression_with_bracket_notation
OK
[{"key": 42}]


queries/root_on_scalar_true
OK
[true]


queries/filter_expression_with_single_equal
OK
[{"key": 42}, {"key": "42"}]


queries/filter_expression_with_addition
OK
[{"key+50": 100}]


queries/bracket_notation_with_negative_number_on_short_array
OK
["one element", "one element"]


queries/dot_notation_with_wildcard_after_dot_notation_after_dot_notation_with_wildcard
OK
[42]


queries/filter_expression_with_equals_on_array_of_numbers
ERROR
Error: 'Malformed filter query'


queries/array_slice_with_negative_step
OK
[]


queries/filter_expression_after_dot_notation_with_wildcard_after_recursive_descent
OK
[]


queries/dot_notation_with_non_ASCII_key
OK
["value"]


queries/bracket_notation_with_number_on_short_array
OK
[]


queries/filter_expression_with_value_after_recursive_descent
OK
[{"id": 2}, {"id": 2}, {"id": 2}, {"id": 2}, {"id": {"id": 2}}]


queries/filter_expression_with_equals_with_root_reference
OK
[]


queries/union_with_slice_and_number
OK
[2, 3]


queries/filter_expression_on_object
OK
[{"key": 1}]


queries/parens_notation
OK
[]


queries/bracket_notation_with_quoted_wildcard_literal
OK
["value"]


queries/dot_notation_with_wildcard_after_recursive_descent
OK
["string", "value", 0, 1, [0, 1], {"complex": "string", "primitives": [0, 1]}]


queries/dot_notation_after_union
OK
["ey", "see"]


queries/dot_notation_with_dash
OK
["value"]


queries/array_slice_with_large_number_for_start_end_negative_step
OK
[]


queries/dot_notation_with_empty_path
OK
[{"": 9001, "''": "nice", "key": 42}]


queries/bracket_notation_with_quoted_special_characters_combined
OK
[]


queries/filter_expression_with_different_ungrouped_operators
ERROR
Error: 'Malformed filter query'


queries/filter_expression_with_negation_and_less_than
ERROR
Error: 'Malformed filter query'


queries/bracket_notation_with_quoted_number_on_object
OK
["value"]


queries/dot_notation_after_bracket_notation_after_recursive_descent
OK
[200, 42, 500]


queries/filter_expression_with_equals_string_with_single_quotes
OK
[{"key": "value"}]


queries/array_slice_with_negative_start_and_positive_end_and_range_of_-1
OK
[]


queries/bracket_notation_with_wildcard_after_array_slice
OK
[1, 2, "a", "b"]


queries/array_slice_with_large_number_for_end
SKIPPED


queries/array_slice_with_step_1
OK
["first", "second", "third"]


queries/bracket_notation
OK
["value"]


queries/filter_expression_with_equals_object
OK
[{"d": 0}, {"d": "{\"k\":\"v\"}"}]


queries/dot_bracket_notation
OK
["value"]


queries/filter_expression_with_boolean_or_operator_and_value_false
OK
[{"key": 1}, {"key": 3}, {"key": "nice"}, {"key": {}}, {"key": []}]


queries/bracket_notation_with_number_after_dot_notation_with_wildcard_on_nested_arrays_with_different_length
OK
[3]


queries/dot_notation_with_double_quotes
OK
["value"]


queries/filter_expression_with_equals_number_for_dot_notation_with_star
OK
[]


queries/bracket_notation_with_quoted_current_object_literal
OK
["value"]


queries/bracket_notation_with_two_literals_separated_by_dot_without_quotes
NOT_SUPPORTED
Error: 'Unable to parse token two.some in expression: [two.some]'


queries/filter_expression_without_value
ERROR
Error: 'Malformed filter query'


queries/filter_expression_with_equals_true
OK
[{"key": true}, {"key": "value"}, {"key": 1}, {"key": -1}, {"key": 42}, {"key": {}}]


queries/array_slice_with_step_and_leading_zeros
OK
[10, 20]


queries/union_with_keys_after_array_slice
OK
[]


queries/bracket_notation_with_wildcard_on_array
OK
["string", 42, {"key": "value"}, [0, 1]]


queries/dot_notation_with_key_named_null
OK
["value"]


queries/bracket_notation_with_quoted_double_quote_literal
OK
["value"]


queries/array_slice_with_start_large_negative_number_and_open_end_on_short_array
OK
["third", "first", "second", "third"]


queries/array_slice_on_non_overlapping_array
OK
[]


queries/union_with_keys_on_object_without_key
OK
[]


queries/array_slice_with_open_start_and_negative_step
SKIPPED


queries/filter_expression_with_equals_string_with_current_object_literal
OK
[{"key": "hi@example.com"}]


queries/array_slice_with_negative_step_only
SKIPPED


queries/bracket_notation_with_wildcard_after_recursive_descent
OK
["string", "value", 0, 1, [0, 1], {"complex": "string", "primitives": [0, 1]}]


queries/dot_notation_after_array_slice
OK
["ey", "bee"]


queries/filter_expression_with_equals_null
OK
[{"key": false}, {"key": null}, {"key": ""}, {"key": 0}, {"key": []}]


queries/dot_notation_without_root
OK
["value"]


queries/filter_expression_with_bracket_notation_with_number
OK
[["a", "b"]]


queries/dot_notation_on_empty_object_value
OK
[{}]


queries/dot_notation_with_key_root_literal
NOT_SUPPORTED
Error: 'Unable to parse token $ in expression: .$'


queries/filter_expression_after_recursive_descent
OK
[{"id": 2}, {"id": 2}, {"id": 2}, {"id": 2}]


queries/array_slice_with_step
OK
["first", "third"]


queries/filter_expression_with_boolean_or_operator_and_value_true
OK
[{"key": 1}, {"key": 3}, {"key": "nice"}, {"key": {}}, {"key": []}]


queries/union_with_keys
OK
[]


queries/bracket_notation_with_wildcard_on_null_value_array
OK
[40, null, 42]


queries/filter_expression_with_equals_number_with_leading_zeros
OK
[{"key": "010"}, {"key": "10"}, {"key": 10}]


queries/recursive_descent_after_dot_notation
OK
[[0, 1], {"complex": "string", "primitives": [0, 1]}]


queries/bracket_notation_with_wildcard_after_dot_notation_after_bracket_notation_with_wildcard
OK
[42]


queries/filter_expression_with_value_after_dot_notation_with_wildcard_on_array_of_objects
OK
[]


queries/filter_expression_with_empty_expression
NOT_SUPPORTED
Error: 'Unable to parse token ?() in expression: [?()]'


queries/array_slice_with_step_empty
OK
["second", "third"]


queries/dot_notation
OK
["value"]


queries/array_slice_with_step_only
OK
["first", "third", "fifth"]


queries/dot_notation_after_bracket_notation_with_wildcard_on_some_matching
OK
[1]


queries/union_with_keys_after_recursive_descent
OK
[]


queries/dot_notation_after_recursive_descent
OK
["russian dolls", "something", "top", "value", {"key": "russian dolls"}]


queries/filter_expression_with_equals_string_with_dot_literal
OK
[{"key": "some.value"}]


queries/bracket_notation_with_empty_string
NOT_SUPPORTED
Error: 'Unable to parse token '' in expression: ['']'


queries/dot_bracket_notation_without_quotes
OK
["value"]
```

I also checked it against the upcoming version 0.7.0:

```diff
@@ -303,7 +303,7 @@

 queries/filter_expression_with_regular_expression
 OK
-[]
+[{"name": "hello world"}, {"name": "yes hello world"}]


 queries/filter_expression_without_parens
```

**Comment by cburgmer** [comment]
Manually merged this. Also checked in the changes from running this.

Should we rename the whole implementation or do you prefer keeping the old name?

**Comment by SoftCreatR** [comment]
Well, i only keep the namespace for compatibility reasons. However, renaming is a good idea, i guess.

Either way, what do you think about just adding it as another implementation? This way, you would have a direct comparison between both implementations.

**Comment by SoftCreatR** [comment]
Fyi: Version 0.7.0 has just been released.

**Comment by cburgmer** [comment]
> Fyi: Version 0.7.0 has just been released.

I'm getting the following:

```
PHP Fatal error:  Uncaught TypeError: property_exists() expects parameter 2 to be string, int given in ./json-path-comparison/implementations/PHP_flow-jsonpath/vendor/softcreatr/jsonpath/src/AccessHelper.php:72
Stack trace:
#0 ./json-path-comparison/implementations/PHP_flow-jsonpath/vendor/softcreatr/jsonpath/src/AccessHelper.php(72): property_exists(Object(stdClass), 1)
#1 ./json-path-comparison/implementations/PHP_flow-jsonpath/vendor/softcreatr/jsonpath/src/Filters/IndexFilter.php(23): Flow\JSONPath\AccessHelper::keyExists(Object(stdClass), 1, false)
#2 ./json-path-comparison/implementations/PHP_flow-jsonpath/vendor/softcreatr/jsonpath/src/JSONPath.php(77): Flow\JSONPath\Filters\IndexFilter->filter(Object(stdClass))
#3 ./json-path-comparison/implementations/PHP_flow-jsonpath/main.php(14): Flow\JSONPath\JSONPath->find('$..[1].key')
#4 {main}
  thrown in ./json-path-comparison/implementations/PHP_flow-jsonpath/vendor/softcreatr/jsonpath/src/AccessHelper.php on line 72
```

**Comment by SoftCreatR** [comment]
Interesting find, since my own tests (based on yours) doesn't complain about it. I'll fix this later this day.

**Comment by cburgmer** [comment]
This might be connected to me locally upgrading to PHP 7.4.11. Happy for help on this.

**Comment by SoftCreatR** [comment]
The lib is automatically tested against PHP 7.1, 7.2, 7.3, 7.4 and even 8.0 🤯

**Comment by cburgmer** [comment]
Ah, I believe it's a breaking change in the library + the compose lock file not actually locking the version if I revert.
Mental note to try using "*" instead of "dev-main" in the hopes that his will make the lock file actually useful as it seems to work with the other implementations.

**Comment by SoftCreatR** [comment]
dev-master should be fine. I've just committed a small change, that should fix it. But I'll run your tests, when I find some time.

**Comment by SoftCreatR** [comment]
At least in the current version, I can't reproduce it anymore.

Btw: https://github.com/SoftCreatR/JSONPath/blob/main/tests/QueryTest.php

**Comment by cburgmer** [comment]
Updated and renamed

**Comment by SoftCreatR** [comment]
@cburgmer When are implementations are being updated? Since your last update, two new versions have been released already, which should provide some more fixes.

**Comment by cburgmer** [comment]
Updated in cf0049671fc8b5d8b43dde9f745ecb42a3c5b602.

Updates can be done via `./upgrade.sh && ninja`

**Pull request closed without merging**
