### PR TITLE
Bump JsonPath.Net to v1.0.0

### PR DESCRIPTION
**Pull request by glyn**
See https://github.com/cburgmer/json-path-comparison/issues/143

### CODE REVIEW

**Comment by glyn** [comment]
@gregsdennis Do you think there is more to bumping the version than just this?

**Comment by gregsdennis** [comment]
No. Just bumping should be fine. It's not doing anything custom (like defining functions), so the breaks introduced in 0.8 shouldn't be a problem.

**Review by gregsdennis — APPROVED** [review]

**Review by gregsdennis — CHANGES_REQUESTED** [review]
Change target framework to `net6.0`

**Comment by glyn** [comment]
> Change target framework to `net6.0`. Sorry, missed that initially.

Fixed.

**Review by gregsdennis — APPROVED** [review]
Yep that should be it. I don't see a docker file or anything.

**Comment by cburgmer** [comment]
Merged in 3a122339e232549f91d788adca0f8395d19b322d

**Pull request closed without merging**
