### PR TITLE
Add json-p3

### PR DESCRIPTION
**Pull request by jg-rp**
Add [JSON P3](https://github.com/jg-rp/json-p3) for comparison. JSON P3 follows RFC 9535 and tests against the JSONPath Compliance Test Suite.

### CODE REVIEW

**Comment by cburgmer** [comment]
Running this locally fails with the following, most likely because the syntax is not (yet) supported by the nodejs 12 shipped via the current Dockerfile.

```
FAILED: build/test_compilation/JavaScript_json-p3
LANG=en_US.UTF-8 LC_ALL= LC_COLLATE=C bash -c "diff --ignore-space-change <(echo 42) <(implementations/JavaScript_json-p3/run.sh ''\\$''[1]'' <<< '[0, 42]' | tr -d ' \n') || diff --ignore-space-change <(echo '[42]') <(implementations/JavaScript_json-p3/run.sh ''\\$''[1]'' <<< '[0, 42]' | tr -d ' \n')" > build/test_compilation/JavaScript_json-p3
/json-path-comparison/implementations/JavaScript_json-p3/node_modules/json-p3/dist/json-p3.cjs.js:1087
    this.cacheSize = options.cacheSize ?? 10;
                                        ^

SyntaxError: Unexpected token '?'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/json-path-comparison/implementations/JavaScript_json-p3/index.js:3:20)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
/json-path-comparison/implementations/JavaScript_json-p3/node_modules/json-p3/dist/json-p3.cjs.js:1087
    this.cacheSize = options.cacheSize ?? 10;
                                        ^

SyntaxError: Unexpected token '?'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/json-path-comparison/implementations/JavaScript_json-p3/index.js:3:20)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
```

```
./src/with_docker.sh node --version
[...]
v12.22.9
```

**Comment by jg-rp** [comment]
Thanks for looking at this, @cburgmer. Would you consider a PR that adds [Node Version Manager](https://github.com/nvm-sh/nvm) as a dependency, so we can install the latest LTS version of Node.js?

**Comment by cburgmer** [comment]
I was in the process of bumping Ubuntu to the latest LTS, so maybe we can
forgo adding more dependencies for now.

**Comment by cburgmer** [comment]
Merged manually.
Thanks for adding!

**Pull request closed without merging**
