### PR TITLE
Add Haskell implementation

### PR DESCRIPTION
**Pull request by akshaymankar**
Fixes akshaymankar/jsonpath-hs#2

Few notes:
- The implementation doesn't pin any version of the library, please let me know if it should
- The library doesn't support filtering as of now so most of the those queries error. I wouldn't have mentioned this here, but some queries have lost consensus because of this. Maybe errors shouldn't be part of consensus?

### CODE REVIEW

**Comment by cburgmer** [comment]
Thanks a lot! Will run it once locally once I have good Internet and then plan to merge.

**Comment by cburgmer** [comment]
Seeing a local diff I cannot explain right now:
```
diff --cc docs/errors.html
index 5161f78,5161f78..c961905
--- a/docs/errors.html
+++ b/docs/errors.html
@@@ -214,7 -214,7 +214,7 @@@ Golang (github.com-oliveagle-jsonpath)
  Haskell (jsonpath), Array index slice negative step
  </h3>

--<pre><code>implementations/Haskell_jsonpath/run.sh: line 6: 32611 Killed                  "$script_dir"/build/json-path-comparison "$@"
++<pre><code>implementations/Haskell_jsonpath/run.sh: line 6: 11278 Killed                  "$script_dir"/build/json-path-comparison "$@"
  </code></pre>

  <h3 id="JavaScript_Goessner___array_index_slice_negative_step">
@@@ -580,7 -580,7 +580,7 @@@ Golang (github.com-oliveagle-jsonpath)
  Haskell (jsonpath), Array index slice start end step 0
  </h3>

--<pre><code>implementations/Haskell_jsonpath/run.sh: line 6: 36566 Killed                  "$script_dir"/build/json-path-comparison "$@"
++<pre><code>implementations/Haskell_jsonpath/run.sh: line 6: 11460 Killed                  "$script_dir"/build/json-path-comparison "$@"
  </code></pre>

  <h3 id="JavaScript_Goessner___array_index_slice_start_end_step_0">
```

**Comment by cburgmer** [comment]
- Pinning will help to have a stable result, but it's not a must for me personally :)
- My stance so far is that it's a slippery slope defining who is allowed to contribute to the consensus and who doesn't. If we want to exclude a library from contributing negatively, we should find an objective criteria. Even better if this can be somewhat determined programmatically. Happy to track that in a dedicated issue. So for now I would say, don't worry!

**Comment by akshaymankar** [comment]
* The numbers in the diff are pids, I think they are printed by the kernel when it OOMKills the process. My guess is kernel has to kill the program because the it is going into an infinite loop.
For now, every run would produce this diff, not sure what can be done except for fixing this upstream. I will create an issue for this and fix it at some point.
* I will pin the version and send another PR and also add a script to bump it.
* I agree that exclusion from consensus would require deeper thought, dedicated issue would be good.

**Pull request merged**
