### PR TITLE
Add python-jsonpath

### PR DESCRIPTION
**Pull request by jg-rp**
This pull request adds [Python JSONPath](https://github.com/jg-rp/python-jsonpath), another JSONPath implementation for Python.

It follows most of the IETF JSONPath Draft. See [compliance.py](https://github.com/jg-rp/python-jsonpath/blob/main/tests/compliance.py) and [consensus.py](https://github.com/jg-rp/python-jsonpath/blob/main/tests/consensus.py) for test cases that have been deliberately skipped, and the [docs](https://jg-rp.github.io/python-jsonpath/syntax/#notable-differences) for a description of known differences.

### CODE REVIEW

**Comment by cburgmer** [comment]
Thanks for the PR.

Running the script locally fails to build on my machine (using Docker) with the following:

```
[70/1381] LANG=en_US.UTF-8 LC_ALL= LC_COLLATE=C ./src/query_implementation.sh queries/bracket_notation_with_number_on_string implementations/Python_python-jsonpath > 'build/results/bracket_notation_with_number_on_string/Python_python-jsonpath'
FAILED: build/results/bracket_notation_with_number_on_string/Python_python-jsonpath
LANG=en_US.UTF-8 LC_ALL= LC_COLLATE=C ./src/query_implementation.sh queries/bracket_notation_with_number_on_string implementations/Python_python-jsonpath > 'build/results/bracket_notation_with_number_on_string/Python_python-jsonpath'
```

The output is here:
```
$ cat build/results/bracket_notation_with_number_on_string/Python_python-jsonpath
ERROR
This error message includes an absolute path which will make it hard to reproduce on other machines.
Please change the script to error without it.

Traceback (most recent call last):
  File "/json-path-comparison/implementations/Python_python-jsonpath/main.py", line 25, in <module>
    sys.exit(main())
  File "/json-path-comparison/implementations/Python_python-jsonpath/main.py", line 16, in main
    results = path.findall(j)
  File "/json-path-comparison/implementations/Python_python-jsonpath/build/deps/local/lib/python3.10/dist-packages/jsonpath/path.py", line 83, in findall
    _data = json.loads(data)
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by jg-rp** [comment]
Thanks, @cburgmer.

I've updated the test runner (main.py) with a catch-all try/except, similar to the `Python_jsonpath2` implementation.

In the case of "bracket_notation_with_number_on_string",  the document does not seem to be valid JSON, hence the `JSONDecodeError`.

https://github.com/cburgmer/json-path-comparison/blob/18d44ea9d12abc0ccace1df0523dcc0a8233c8e3/regression_suite/regression_suite.yaml#L288-L290

So far I've only managed to do spot checks locally with `./src/query_implementation.sh`. My attempts at a docker build have resulted in `ninja: build stopped: subcommand failed.` It's not immediately obvious to me which subcommand is failing.

**Comment by cburgmer** [comment]
Thanks for the fix. Merged!

In my understanding the document is valid. Node for example is happy to parse it:

```
$ node
Welcome to Node.js v20.3.1.
Type ".help" for more information.
> JSON.parse('"nice"')
'nice'
```

**Comment by jg-rp** [comment]
You are absolutely right. I see now that the top-level object/array restriction was removed in RFC 7159.

Thanks again.

**Pull request merged**
