### PR TITLE
remorhaz/php-json-path implementation added

### PR DESCRIPTION
**Pull request by remorhaz**
Hello!

I've added my implementation of JsonPath, using Flow implementation as an example. Lots of files seem to change after running the build; please check if that's okay.

Another wierd thing I've noticed is running `composer update` for Flow implementation while storing lock file. For my implementation I decided to run `composer install`, but I didn't have enough courage to change it for Flow.

And thank you for your work, I think it's very important.

### CODE REVIEW

**Comment by cburgmer** [comment]
Thanks for the PR.

It looks like you triggered an issue connected to #1 where the Clojure (and Kotlin) report cannot complete because of a consensus outcome that changed with the addition of this library here. You probably also see the ./go script failing on your side at one of the latest steps (thus not completing the overall report).

We need to look at this issue before we can merge this PR. The error happens in ./src/compile_regression_suite.sh one lines 54 and 63 (only for libraries which return scalar results).

All the changes you see in your PR stem from the consensus triggering changes as your library addition tips the balance in a few cases. All the outputs are checked into Git for ease of review and deployment.

**Comment by remorhaz** [comment]
After investigating the behavior of other implementations I decided to make some improvements in mine:

https://github.com/remorhaz/php-json-path/issues/8
https://github.com/remorhaz/php-json-path/issues/9

I hope it won't take much time, so I think it's rational to re-review the impact of my library on the consensus after upgrade.

But nevertheless, the problem of eventually changing consensus stays. Adding new implementation can always break existing consensus or create the new one; but I don't think we should consider this as a _regression_ of existing implementations, because the "breaking" change is not in the implementation itself - the "standard" is what changes, and that change can be caused by _any_ implementation and/or the scope change.

**Comment by cburgmer** [comment]
One small finding unrelated to the issue above: Your commit changes the file `implementations/PHP_galbar-jsonpath/composer.lock` subtly with a different order (https://github.com/cburgmer/json-path-comparison/pull/6/commits/2f5d8939a1c600ad602727e8b804ba25b1a5f34a#diff-c9046fe927da0104cd57c3e68331abde). Re-running `./src/wrap_in_docker.sh ./go` on my machine undoes that change again. It seems you have more PHP experience than I do, do you have an idea what is different on our machines that causes that change?

**Comment by cburgmer** [comment]
On the "changing consensus" issue, I agree that this is an issue whenever another implementation is added. Two things though make me believe that this will eventually stabilise:

1. There's only so many different implementations of JsonPath, additions radically changing the consensus will become less frequent
2. Libraries will hopefully converge (after all that's one goal of this project), making the consensus stronger and less likely to change.

Happy to discuss though, probably in a new issue? I do like your summary, we could add this to the README?

**Comment by cburgmer** [comment]
I removed the 4 queries which triggered the failure mentioned above. This is committed to master. Could you rebase and re-run to see whether this fixes everything?

I feel we should bring back those 4 queries removed, but let's discuss in #1 how to handle those better.

**Comment by cburgmer** [comment]
If you rebase, you'll have all the conflicts in `./regression_suite`. It's probably easiest to throw them away and rebuild via `./go`.

**Comment by remorhaz** [comment]
Yes, I will check it this evening, but I really don't think we should hurry with merging this commit; we should rather estimate the way we proceed with "auto-altering standard". I will create an issue with some of my thoughts about it a bit later.

**Comment by cburgmer** [comment]
If you want an example for a big change in consensus due to a new library, have a look at this branch: https://github.com/cburgmer/json-path-comparison/tree/Golang_github.com-yalp-jsonpath

**Comment by remorhaz** [comment]
I've resolved all the conflicts (and upgraded my library), so I'guess we can safely merge ths PR.

**Comment by cburgmer** [comment]
Looks good! Do you want to merge it?

**Pull request merged**
