### PR TITLE
update jsonpath.net to v0.3.1 (aligns with spec)

### PR DESCRIPTION
**Pull request by gregsdennis**
I recently made quite a few changes to my library to bring it into alignment with the current spec.

### CODE REVIEW

**Comment by glyn** [comment]
@gregsdennis Happy to bump to v0.3.1, but for the record, which version of the spec does this align with?

**Comment by gregsdennis** [comment]
It aligns with the current master in the repo (maybe plus your function pr).

**Comment by glyn** [comment]
Ok, thanks.

**Comment by cburgmer** [comment]
Merged in fcd354f2748253c2ee7b1d859f9a7b064d19d04f

**Pull request closed without merging**
