### PR TITLE
Compare set wise comparisons in filter expressions

### PR DESCRIPTION
**Pull request by glyn**
Anyone who likes math(s) may care to read about the [properties](https://github.com/vmware-labs/yaml-jsonpath/issues/3#issuecomment-648236076) these set wise operations may or may not have.

### CODE REVIEW

**Comment by cburgmer** [comment]
I usually re-run the changes locally, to double check the differences across Docker and OSX native (the difference is becoming slightly costly).

I found a few issues that I fixed in separate commits:
dbd31ca55ea1de56daea8313445792a107a50b92 shows that Ruby ran into timeouts. I'll try to reproduce.
(and 2e56731407ac7b55f20e114743745430485101d4 shows smaller differences across the runtimes I'll try to further minimise).

**Comment by cburgmer** [comment]
Oh, and I hope it was OK to merge. 
I was easier for me to investigate the resulting diff on my machine.

**Comment by glyn** [comment]
> Oh, and I hope it was OK to merge.

It wasn't (just) OK - it was really helpful. Thanks! In particular, I don't want to install all the language runtimes locally if I can help it...

**Comment by cburgmer** [comment]
I think the Docker setup helps a lot. For me it's just too slow though, so I'm basically managing both. And while the successful responses are (mostly) all equal across the platforms, implementations seem to deviate a lot on error messages. Also version differences come into play here.
I started actively removing the differences, and just committed some more, so that the differences you saw in your commit now should be gone.
Until the next version bump, or new query which triggers a new corner case.

**Pull request merged**
