### PR TITLE
Add ANALYSIS document

### PR DESCRIPTION
**Pull request by danielaparker**
Further to [issue \#95](https://github.com/cburgmer/json-path-comparison/issues/95), I started an ANALYSIS.md document that hopefully could be a starting point for analyzing the data in the project. If you think it's a worthwhile addition, I'll continue to add content as time permits. Of course, others would be welcome to contribute new content, and to provide feedback on existing content.

### CODE REVIEW

**Review by glyn — COMMENTED** [review]
I like the idea, but the current document is probably the tip of an iceberg. So would it be worth making some statement about the incompleteness of the analysis near the top of the document (and inviting contributions)?

**Comment by danielaparker** [comment]
> I like the idea, but the current document is probably the tip of an iceberg. So would it be worth making some statement about the incompleteness of the analysis near the top of the document (and inviting contributions)?

Yes, on both points.

**Comment by danielaparker** [comment]
An alternative would be to enable Wikis for the site, make it editable by anyone, and move this content there.

**Comment by glyn** [comment]
> An alternative would be to enable Wikis for the site, make it editable by anyone, and move this content there.

I think a wiki wouldn't be quite as visible. Also the quality of contributions could deteriorate. Why don't we start with this document and we can always move to a wiki if a cottage industry springs up around it?

**Pull request merged**
